basic:
    name: Skyzone
    environments:
        production: 'https://www.skyzone.com/'
        staging: 'https://skyzone.skybox2.com/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /pineville
        - /richmond
        - /centralphoenix
        - /allendale
        - /phoenix
        - /peoria
        - /east-baltimore
        - /hagerstown
        - /harrisburg
        - /lancaster
        - /ca-moncton
        - /skyzone-coming-soon-park-template
        - /cliftonpark
        - /dayton
        - /durham
        - /fairviewheights
        - /fargo
        - /fenton
        - /florence
        - /fortlauderdale
        - /glenmills
        - /grandrapids
        - /greenville
        - /hampton
        - /irving
        - /jackson
        - /kansascity
        - /lafayette
        - /lasvegas
        - /leessummit
        - /lexington
        - /madison
        - /mcdonough
        - /milwaukee
        - /monroeville
        - /murfreesboro
        - /norwalk
        - /omaha
        - /philadelphia
        - /queensbury
        - /ridgeland
        - /shelbytownship
        - /southplainfield
        - /rockledge-fl
        - /syracuse
        - /ventura
        - /waldorf
        - /westminster
        - /biloxi
        - /chandler
        - /douglasville
        - /gresham
        - /louisville-ky
        - /north-tampa
        - /pembrokepines
        - /queens
        - /clearwater
        - /edmond
        - /pittston
        - /greensboro
        - /cedarrapids
        - /burlington
        - /alhambra
        - /desmoines
        - /chalfont
        - /ocala
        - /canonsburg
        - /macon
        - /columbiamo
        - /canton
        - /greenfield
        - /hamilton
        - /topeka
        - /bethlehem-lehigh-valley-pa
        - /charleston-wv
        - /beldenvillage
        - /cutlerbay
        - /doral
        - /springfieldil
        - /elmhurst
        - /evansville
        - /charleston
        - /siouxfalls
        - /pinebrook
        - /cerritos
        - /coloradosprings
        - /tulsa
        - /myrtlebeach
        - /aurora
        - /fremont
        - /sarasota
        - /moorestown
        - /plainfield
        - /buford
        - /covina
        - /lima
        - /rutherford
        - /north-bergen
        - /smyrna
        - /san-bernardino
        - /virginia-beach
        - /bostonheights
        - /carlsbad
        - /clermont
        - /elpasoeast
        - /elpasowest
        - /indysouth
        - /lakewood
        - /lascruces
        - /laveen
        - /manchester
        - /raleigh
        - /sanmarcos
        - /schererville
        - /stockton
        - /highlands-ranch
        - /saratoga-springs
        - /montgomery
        - /bismarck
        - /vacaville
        - /santa-ana
        - /santa-maria
        - /warner-robins-ga
        - /westmont-il
        - /elk-grove
        - /silicon-valley
        - /columbus-ga
        - /gilroy
        - /trumbull
        - /chino-hills
        - /owings-mills-md
        - /schaumburg-il
        - /palmdale
        - /frederick
        - /arlington
        - /alexandria
        - /tracy
        - /irvine
        - /fullerton
        - /hartford
        - /castle-rock
        - /bergen
        - /pico-rivera
        - /arlington-heights
        - /walnut-creek-ca
        - /clay
        - /san-diego-miramar-ca
        - /ofallon-mo
        - /st-louis-shrewsbury-mo
        - /crofton-gambrills-md
        - /easton-lehigh-valley-pa
        - /brown-deer-wi
        - /culver-city-los-angeles-ca
        - /bronx-ny
        - /lansing-il
        - /alsip-il
        - /chicago-midway-il
        - /moreno-valley-ca
        - /bakersfield-ca
        - /san-jose-cambrian-ca
        - /east-haven-ct
        - /glen-burnie-md
        - /turnersville-nj
        - /waco-tx
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
